version: '3.8'

services:
  animal-service:
    build: ./animal-service
    ports:
      - "8000:8000"

  notification-service:
    build: ./notification-service
    ports:
      - "8001:8001"